-
  name: Test ping functionality using ansible
  hosts: web_nodes
  tasks:
    -
      name: Execute ping test using ansible for localhost
      ping:
      tags: done
    -
      name: "Ensure that remote host reboots successfully"
      reboot:
        msg: "Testing the system reboot initiated using ansible"
        pre_reboot_delay: 60
        reboot_timeout: 1200
        test_command: "cat < ansible --version"
