-
  name: Test connection to a server and then install apache
  hosts: web_nodes
  tasks:
    -
      name: Execute ping test using ansible for localhost
      ping:
      tags: done

    - name: check for apache
      shell: "service apache2 status"
      register: _svc_apache
      failed_when: >
        _svc_apache.rc != 0 and (
        "unrecognized service" not in _svc_apache.stderr
        )

    - name: disable apache
      service: name=apache2 state=stopped enabled=no
      when: "_svc_apache.rc == 0"
